[workspace]
authors = ["danteturay <dante.tuary@yahoo.co.uk>"]
channels = ["robostack-humble", "conda-forge"]
name = "go2_guide_dog"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-ros-gz-bridge = ">=0.244.24,<0.245"
ros-humble-ros-gz-sim = ">=0.244.24,<0.245"
gz-msgs = ">=12.0.1,<13"
gz-msgs10 = ">=10.3.2,<11"
